# -*- coding: utf-8 -*-
# Copyright (C) 2023 Benjamin Thomas Schwertfeger
# GitHub: https://github.com/btschwertfeger
#
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: check-ast
      - id: check-toml
      - id: check-docstring-first
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ["--maxkb=500"]
      - id: check-executables-have-shebangs
      - id: trailing-whitespace
      - id: fix-byte-order-marker
      - id: fix-encoding-pragma
      - id: mixed-line-ending
      - id: requirements-txt-fixer
      - id: end-of-file-fixer
      - id: detect-private-key
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-use-type-annotations
      - id: rst-backticks
      # - id: rst-inline-touching-normal
      - id: rst-directive-colons
      - id: text-unicode-replacement-char
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args:
          - --profile=black # solves conflicts between black and isort
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args:
          - --select=E9,F63,F7,F82
          - --show-source
          - --statistics
  - repo: https://github.com/pycqa/pylint
    rev: v2.17.5
    hooks:
      - id: pylint
        name: pylint
        types: [python]
        exclude: ^examples/|^tests/|^setup.py$
        args:
          - --rcfile=pyproject.toml
          - -d=R0801 # ignore duplicate code
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.285
    hooks:
      - id: ruff
        args:
          - --fix
          - --exit-non-zero-on-fix
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
        name: mypy
        additional_dependencies: ["types-requests"]
        pass_filenames: false
        args:
          - --config-file=pyproject.toml
          # - --install-types # do not use within pre-commit
          # - --non-interactive # same here
          - kraken
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.2
    hooks:
      - id: prettier
ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit.com hooks

    for more information, see https://pre-commit.ci
  autofix_prs: false
  autoupdate_branch: ""
  autoupdate_commit_msg: "[pre-commit.ci] pre-commit autoupdate"
  autoupdate_schedule: weekly
  skip: []
  submodules: false
