# -*- coding: utf-8 -*-
# Copyright (C) 2023 Benjamin Thomas Schwertfeger
# GitHub: https://github.com/btschwertfeger
#
# Template workflow to build the project for a specific os
# and Python version.
#

name: Build

on:
  workflow_call:
    inputs:
      os:
        type: string
        required: true
      python-version:
        type: string
        required: true

permissions:
  contents: read

jobs:
  Build:
    runs-on: ${{ inputs.os }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            files.pythonhosted.org:443
            github.com:443
            objects.githubusercontent.com:443
            pypi.org:443

      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0 # IMPORTANT: otherwise the current tag does not get fetched and the build version gets worse

      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Check git status (not Windows)
        if: runner.os != 'Windows'
        run: |
          if [[ -z "$(git status --porcelain)" ]]; then
            echo "No changes found."
          else
            echo "Changes detected. Please commit or discard changes before publishing."
            git status --porcelain
            exit 1
          fi

      - name: Check git status (Windows)
        if: runner.os == 'Windows'
        run: |
          if (-not (git status --porcelain)) {
              Write-Output "No changes found."
          } else {
              Write-Output "Changes detected. Please commit or discard changes before publishing."
              git status --porcelain
              exit 1
          }

      - name: Build Linux
        if: runner.os == 'linux'
        run: |
          uv build .
          uv pip install dist/python_kraken_sdk*.whl

      - name: Build macOS
        if: runner.os == 'macOS'
        run: |
          uv build .
          uv pip install dist/python_kraken_sdk*.whl

      - name: Build Windows
        if: runner.os == 'Windows'
        run: |
          uv build .
          try {
              $WHEEL = Get-ChildItem -Path . -Filter "python_kraken_sdk*.whl" -ErrorAction Stop
              python -m pip install --user $WHEEL
          } catch {
              Write-Error "Error: .whl file not found in the current directory."
              exit 1
          }

      - name: Store the distribution packages
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
        # upload artifacts with the oldest supported version
        if: runner.os == 'linux' && inputs.python-version == '3.11'
        with:
          name: python-package-distributions
          path: dist/
