# -*- mode: yaml; coding: utf-8 -*-
# Copyright (C) 2023 Benjamin Thomas Schwertfeger
# All rights reserved.
# https://github.com/btschwertfeger
#
# Template workflow to build the project for a specific os
# and Python version, run the tests and upload the results to codecov.
#

name: CodeCov

on:
  workflow_call:
    inputs:
      os:
        type: string
        required: true
      python-version:
        type: string
        required: true
    secrets:
      CODECOV_TOKEN:
        required: true
      SPOT_API_KEY:
        required: true
      SPOT_SECRET_KEY:
        required: true
      FUTURES_API_KEY:
        required: true
      FUTURES_SECRET_KEY:
        required: true
      FUTURES_SANDBOX_KEY:
        required: true
      FUTURES_SANDBOX_SECRET:
        required: true

permissions:
  contents: read

jobs:
  CodeCov:
    name: Coverage
    runs-on: ${{ inputs.os }}
    timeout-minutes: 30
    env:
      OS: ${{ inputs.os }}
      PYTHON: ${{ inputs.python-version }}

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@cb605e52c26070c328afc4562f0b4ada7618a84e # v2.10.4
        with:
          disable-sudo: true
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install package
        run: |
          uv venv
          source .venv/bin/activate
          echo ${GITHUB_WORKSPACE}/.venv/bin >> $GITHUB_PATH
          uv pip install ".[test,dev]"

      - name: Generate coverage report
        env:
          SPOT_API_KEY: ${{ secrets.SPOT_API_KEY }}
          SPOT_SECRET_KEY: ${{ secrets.SPOT_SECRET_KEY }}
          FUTURES_API_KEY: ${{ secrets.FUTURES_API_KEY }}
          FUTURES_SECRET_KEY: ${{ secrets.FUTURES_SECRET_KEY }}
          FUTURES_SANDBOX_KEY: ${{ secrets.FUTURES_SANDBOX_KEY }}
          FUTURES_SANDBOX_SECRET: ${{ secrets.FUTURES_SANDBOX_SECRET }}
        run: pytest -vv --cov=kraken --cov-report=xml:coverage.xml --cov-report=term tests

      - name: Export coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@13ce06bfc6bbe3ecf90edbbf1bc32fe5978ca1d3 # v5.3.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
          env_vars: OS,PYTHON
          fail_ci_if_error: false
          flags: unittests
          name: codecov-umbrella
          verbose: true
