# -*- coding: utf-8 -*-
# Copyright (C) 2023 Benjamin Thomas Schwertfeger
# GitHub: https://github.com/btschwertfeger
#
# Template workflow to build the project for a specific os
# and Python version, run the tests and upload the results to codecov.
#

name: CodeCov

on:
  workflow_call:
    inputs:
      os:
        type: string
        required: true
      python-version:
        type: string
        required: true
    secrets:
      CODECOV_TOKEN:
        required: true
      SPOT_API_KEY:
        required: true
      SPOT_SECRET_KEY:
        required: true
      FUTURES_API_KEY:
        required: true
      FUTURES_SECRET_KEY:
        required: true
      FUTURES_SANDBOX_KEY:
        required: true
      FUTURES_SANDBOX_SECRET:
        required: true

permissions:
  contents: read

jobs:
  CodeCov:
    name: Coverage
    runs-on: ${{ inputs.os }}
    env:
      OS: ${{ inputs.os }}
      PYTHON: ${{ inputs.python-version }}

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.codecov.io:443
            api.kraken.com:443
            cli.codecov.io:443
            demo-futures.kraken.com:443
            files.pythonhosted.org:443
            futures.kraken.com:443
            github.com:443
            pypi.org:443
            storage.googleapis.com:443
            ws-auth.kraken.com:443
            ws.kraken.com:443

      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@39cd14951b08e74b54015e9e001cdefcf80e669f # v5.1.1
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install dependencies
        run: python -m pip install --upgrade pip

      - name: Install package
        run: python -m pip install ".[dev,test]"

      - name: Generate coverage report
        env:
          SPOT_API_KEY: ${{ secrets.SPOT_API_KEY }}
          SPOT_SECRET_KEY: ${{ secrets.SPOT_SECRET_KEY }}
          FUTURES_API_KEY: ${{ secrets.FUTURES_API_KEY }}
          FUTURES_SECRET_KEY: ${{ secrets.FUTURES_SECRET_KEY }}
          FUTURES_SANDBOX_KEY: ${{ secrets.FUTURES_SANDBOX_KEY }}
          FUTURES_SANDBOX_SECRET: ${{ secrets.FUTURES_SANDBOX_SECRET }}
        run: pytest -vv --cov --cov-report=xml:coverage.xml tests

      - name: Export coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@e28ff129e5465c2c0dcc6f003fc735cb6ae0c673 # v4.5.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
          env_vars: OS,PYTHON
          fail_ci_if_error: false
          flags: unittests
          name: codecov-umbrella
          verbose: true
