# -*- mode: yaml; coding: utf-8 -*-
# Copyright (C) 2023 Benjamin Thomas Schwertfeger
# All rights reserved.
# https://github.com/btschwertfeger
#
# Template workflow to test the public NFT endpoints
# of the python-kraken-sdk.
#

name: Test NFT

on:
  workflow_call:
    inputs:
      os:
        type: string
        required: true
      python-version:
        type: string
        required: true

permissions:
  contents: read

jobs:
  Test-NFT:
    name: Test ${{ inputs.os }} ${{ inputs.python-version }}
    runs-on: ${{ inputs.os }}
    timeout-minutes: 5
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@cb605e52c26070c328afc4562f0b4ada7618a84e # v2.10.4
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            api.kraken.com:443
            files.pythonhosted.org:443
            github.com:443
            objects.githubusercontent.com:443
            pypi.org:443

      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install package (Linux or macOS)
        if: runner.os != 'Windows'
        run: |
          uv venv
          source .venv/bin/activate
          echo ${GITHUB_WORKSPACE}/.venv/bin >> $GITHUB_PATH
          uv pip install ".[test]"

      - name: Install package (Windows)
        if: runner.os == 'Windows'
        run: |
          uv venv
          .venv\Scripts\activate.ps1
          echo "$env:GITHUB_WORKSPACE\.venv\Scripts" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          uv pip install ".[test]"

      - name: Testing Spot NFT endpoints
        run: pytest -vv -m "nft and not nft_auth" tests
