# -*- coding: utf-8 -*-
# Copyright (C) 2023 Benjamin Thomas Schwertfeger
# Github: https://github.com/btschwertfeger
#
# Template workflow to test the Futures endpoints of the python-kraken-sdk.
# Runs tests for:
#   * Futures REST clients
#   * Futures websocket client
#

name: Test Futures

on:
  workflow_call:
    inputs:
      os:
        type: string
        required: true
      python-version:
        type: string
        required: true

jobs:
  Test-Futures:
    name: Test ${{ inputs.os }} ${{ inputs.python-version }}
    runs-on: ${{ inputs.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest

      - name: Install package
        run: python -m pip install .

      ##    Unit tests of the Futures REST clients and endpoints
      ##
      - name: Testing Futures REST endpoints
        env:
          FUTURES_API_KEY: ${{ secrets.FUTURES_API_KEY }}
          FUTURES_SECRET_KEY: ${{ secrets.FUTURES_SECRET_KEY }}
          FUTURES_SANDBOX_KEY: ${{ secrets.FUTURES_SANDBOX_KEY }}
          FUTURES_SANDBOX_SECRET: ${{ secrets.FUTURES_SANDBOX_SECRET }}
        run: |
          pytest tests/test_futures_rest.py

      ##    Unit tests of the Futures websocket client
      ##
      - name: Testing Futures websocket client
        env:
          FUTURES_API_KEY: ${{ secrets.FUTURES_API_KEY }}
          FUTURES_SECRET_KEY: ${{ secrets.FUTURES_SECRET_KEY }}
          FUTURES_SANDBOX_KEY: ${{ secrets.FUTURES_SANDBOX_KEY }}
          FUTURES_SANDBOX_SECRET: ${{ secrets.FUTURES_SANDBOX_SECRET }}
        run: |
          pytest tests/test_futures_websocket.py
