# -*- coding: utf-8 -*-
# Copyright (C) 2023 Benjamin Thomas Schwertfeger
# GitHub: https://github.com/btschwertfeger
#
# Template workflow to test the private Futures endpoints
# of the python-kraken-sdk.
# Runs tests for:
#   * Futures REST clients
#   * Futures websocket client
#

name: Test Futures

on:
  workflow_call:
    inputs:
      os:
        type: string
        required: true
      python-version:
        type: string
        required: true
    secrets:
      FUTURES_API_KEY:
        required: true
      FUTURES_SECRET_KEY:
        required: true
      FUTURES_SANDBOX_KEY:
        required: true
      FUTURES_SANDBOX_SECRET:
        required: true

permissions:
  contents: read

jobs:
  Test-Futures:
    name: Test ${{ inputs.os }} ${{ inputs.python-version }}
    runs-on: ${{ inputs.os }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0d381219ddf674d61a7572ddd19d7941e271515c # v2.9.0
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            demo-futures.kraken.com:443
            files.pythonhosted.org:443
            futures.kraken.com:443
            github.com:443
            pypi.org:443

      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@39cd14951b08e74b54015e9e001cdefcf80e669f # v5.1.1
        with:
          python-version: ${{ inputs.python-version }}

      - name: Update Pip
        run: |
          python -m pip install --user --upgrade pip

      - name: Install package
        run: python -m pip install --user ".[test]"

      ##    Unit tests of the private Futures REST clients and endpoints
      ##
      - name: Testing Futures REST endpoints
        env:
          FUTURES_API_KEY: ${{ secrets.FUTURES_API_KEY }}
          FUTURES_SECRET_KEY: ${{ secrets.FUTURES_SECRET_KEY }}
          FUTURES_SANDBOX_KEY: ${{ secrets.FUTURES_SANDBOX_KEY }}
          FUTURES_SANDBOX_SECRET: ${{ secrets.FUTURES_SANDBOX_SECRET }}
        run: pytest -vv -m "futures_auth and not futures_websocket and not flaky" tests

      ##    Unit tests of the Futures websocket client
      ##
      - name: Testing Futures websocket client
        env:
          FUTURES_API_KEY: ${{ secrets.FUTURES_API_KEY }}
          FUTURES_SECRET_KEY: ${{ secrets.FUTURES_SECRET_KEY }}
          FUTURES_SANDBOX_KEY: ${{ secrets.FUTURES_SANDBOX_KEY }}
          FUTURES_SANDBOX_SECRET: ${{ secrets.FUTURES_SANDBOX_SECRET }}
        run: pytest -vv -m "futures_websocket and not flaky" tests
