# -*- coding: utf-8 -*-
# Copyright (C) 2023 Benjamin Thomas Schwertfeger
# Github: https://github.com/btschwertfeger
#
# Runs unittests for pyhton3.7, python3.8, ..., pyhton3.11 using manual trigger
#

name: Additional Test Jobs

on:
  workflow_dispatch:
    # inputs:
    #   os:
    #     type: choice
    #     description: OS image to test with
    #     options: ["macos-latest", "ubuntu-latest", "windows-latest"]
    #     required: true
    #   python-version:
    #     type: choice
    #     description: Python version to run the tests
    #     options: ["3.7", "3.8", "3.9", "3.10", "3.11"]

concurrency:
  group: ADDITIONAL_TESTS-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Test:
    uses: ./.github/workflows/test.yml
    strategy:
      fail-fast: false
      max-parallel: 1 # to avoid failing tests because of API Rate limits
      matrix:
        os: ["macos-latest", "ubuntu-latest", "windows-latest"]
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
    secrets: inherit
