# -*- coding: utf-8 -*-
# Copyright (C) 2023 Benjamin Thomas Schwertfeger
# Github: https://github.com/btschwertfeger
#
# Workflow to apply pre-commit, build, test and upload the package
# to the test index of PyPI.

name: CI/CD

on:
  push:
    branches:
      - "**"

concurrency:
  group: CICD-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ## ==========================================================================
  ##    Checks the code logic, style and more
  ##
  Pre-Commit:
    uses: ./.github/workflows/_pre_commit.yml

  ## ==========================================================================
  ##  Discover vulnerabilities
  ##
  CodeQL:
    uses: ./.github/workflows/_codeql.yml

  ## ==========================================================================
  ##    Builds the package on multiple OS for multiple
  ##    Python versions
  ##
  Build:
    needs: [Pre-Commit]
    uses: ./.github/workflows/_build.yml
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest] #, windows-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}

  ## ==========================================================================
  ##    Build the documentation
  ##
  Build-Doc:
    needs: [Pre-Commit]
    uses: ./.github/workflows/_build_doc.yml
    with:
      os: "ubuntu-latest"
      python-version: "3.11"

  ## ==========================================================================
  ##          Run the Spot tests for Python 3.7 until 3.11
  ##
  ##  (public endpoints)
  ##
  Test-Spot-Public:
    needs: [Build]
    uses: ./.github/workflows/_test_spot_public.yml
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
  ##
  ##  (private endpoints)
  Test-Spot-Private:
    needs: [Build]
    uses: ./.github/workflows/_test_spot_private.yml
    strategy:
      max-parallel: 1 # to avoid failing tests because of API Rate limits
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
    secrets: inherit

  ## ==========================================================================
  ##        Run the Futures tests for Python 3.7 until 3.11
  ##
  ##  (public endpoints)
  Test-Futures-Public:
    needs: [Build]
    uses: ./.github/workflows/_test_futures_public.yml
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
  ##
  ##  (private endpoints)
  Test-Futures-Private:
    needs: [Build]
    uses: ./.github/workflows/_test_futures_private.yml
    strategy:
      max-parallel: 1 # to avoid failing tests because of API Rate limits
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
    secrets: inherit

  ## ==========================================================================
  ##    Uploads the package to test.pypi.org on master if triggered by
  ##    a regular commit/push.
  ##
  UploadTestPyPI:
    if: success() && github.ref == 'refs/heads/master'
    needs:
      [
        Test-Spot-Public,
        Test-Spot-Private,
        Test-Futures-Public,
        Test-Futures-Private,
      ]
    name: Upload current development version to Test PyPI
    uses: ./.github/workflows/_pypi_publish.yml
    with:
      REPOSITORY_URL: https://test.pypi.org/legacy/
    secrets:
      API_TOKEN: ${{ secrets.TEST_PYPI_API_TOKEN }}

  ## ==========================================================================
  ##    Generates and uploads the coverage statistics to codecov
  ##
  CodeCov:
    needs:
      [
        Test-Spot-Public,
        Test-Spot-Private,
        Test-Futures-Public,
        Test-Futures-Private,
      ]
    uses: ./.github/workflows/_codecov.yml
    with:
      os: "ubuntu-latest"
      python-version: "3.11"
    secrets: inherit
