#
# * Builds the package on different os
# * Tests the package for Python 3.11
# * Generate coverage report
#

name: CI/CD

on:
  push:
    branches:
      - "**"

concurrency:
  group: CICD-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Pre-Commit:
    uses: ./.github/workflows/pre_commit.yml

  Build:
    needs: [pre-commit]
    uses: ./.github/workflows/build.yml
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}

  Test:
    needs: [build]
    uses: ./.github/workflows/test.yml
    strategy:
      max-parallel: 1 # to avoid failing tests because of API Rate limits
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.11"]
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
    secrets: inherit

  CodeCov:
    needs: [test]
    uses: ./.github/workflows/codecov.yml
    with:
      os: "ubuntu-latest"
      python-version: "3.11"
    secrets: inherit
