name: TESTUPLOAD

on:
  push:
    branches:
      - "**"

jobs:
  UploadTestPyPI:
    # if: success() && github.ref == 'refs/heads/master'
    name: Upload current development version to Test PyPI
    uses: ./.github/workflows/_pypi_publish.yml
    with:
      REPOSITORY_URL: https://test.pypi.org/legacy/
    secrets:
      API_TOKEN: ${{ secrets.TEST_PYPI_API_TOKEN }}
