name: Pre-Commit

on:
  workflow_call:

jobs:
  pre-commit:
    name: Pre-Commit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: pre-commit/action@v3.0.0
