name: PyPI Release

on:
  release:
    types: [published]

jobs:
  # create-tag:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: rickstaa/action-create-tag@v1
  #       id: "tag_create"
  #       with:
  #         tag: { { github.event.inputs.tag } }
  #         tag_exists_error: true
  #         message: { { github.event.inputs.tag } }
  #     - run: |
  #         echo "Tag already present: ${{ env.TAG_EXISTS }}"

  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for OIDC publishing
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # - name: Set output
      #   id: vars
      #   run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
      # - name: Check output
      #   env:
      #     RELEASE_VERSION: ${{ steps.vars.outputs.tag }}

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install build

      - name: Build the package
        run: python -m build .

      # - name: Publish package distributions to PyPI
      #   uses: pypa/gh-action-pypi-publish@release/v1
      #   with:
      #     password: ${{ secrets.PYPI_API_TOKEN }}
