name: Test

on:
  workflow_call:
    inputs:
      os:
        type: string
        required: true
      python-version:
        type: string
        required: true

jobs:
  Test:
    name: Test ${{ inputs.os }} ${{ inputs.python-version }}
    runs-on: ${{ inputs.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install pytest

      - name: Install package
        run: python -m pip install .

      - name: Testing Spot REST endpoints
        env:
          SPOT_API_KEY: ${{ secrets.SPOT_API_KEY }}
          SPOT_SECRET_KEY: ${{ secrets.SPOT_SECRET_KEY }}
        run: |
          pytest tests/test_spot_rest.py

      - name: Testing Spot websocket client
        env:
          SPOT_API_KEY: ${{ secrets.SPOT_API_KEY }}
          SPOT_SECRET_KEY: ${{ secrets.SPOT_SECRET_KEY }}
        run: |
          pytest tests/test_spot_websocket.py

      - name: Testing Futures REST endpoints
        env:
          FUTURES_API_KEY: ${{ secrets.FUTURES_API_KEY }}
          FUTURES_SECRET_KEY: ${{ secrets.FUTURES_SECRET_KEY }}
          FUTURES_SANDBOX_KEY: ${{ secrets.FUTURES_SANDBOX_KEY }}
          FUTURES_SANDBOX_SECRET: ${{ secrets.FUTURES_SANDBOX_SECRET }}
        run: |
          pytest tests/test_futures_rest.py

      - name: Testing Futures websocket client
        env:
          FUTURES_API_KEY: ${{ secrets.FUTURES_API_KEY }}
          FUTURES_SECRET_KEY: ${{ secrets.FUTURES_SECRET_KEY }}
          FUTURES_SANDBOX_KEY: ${{ secrets.FUTURES_SANDBOX_KEY }}
          FUTURES_SANDBOX_SECRET: ${{ secrets.FUTURES_SANDBOX_SECRET }}
        run: |
          pytest tests/test_futures_websocket.py
